project:
  type: website
  output-dir: docs

website:
  title: "Luqman Abu El Foul"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: research.qmd
        text: "Research"
      - href: teaching.qmd
        text: "Teaching"
      - href: cv.qmd
        text: "CV"

format:
  html:
    theme:
      - sandstone
      - brand
    css: styles.css
    toc: true

editor: visual

