---
title: "Research"
---

## Publications

- Abu El Foul, Luqman, “[Rhythms of an Uprising: Indexing the 2021 Unity Intifada through an analysis of Palestinian Rap Music](https://doi.org/10.1080/0377919X.2025.2520187)”, *Journal of Palestine Studies* 54, no. 2 (2025): 6-27 \[DOI: 10.1080/0377919X.2025.2520187\]
<details>
  <summary><em>Abstract</em></summary>
  <p><em> The 2021 Unity Intifada marked a turning point in Palestinian resistance, repoliticizing Palestinian youth in ways unseen since the second intifada. This article traces the evolution of conceptions of resistance among young Palestinian men between 2018 and 2021 through an analysis of Palestinian rap music. Examining the development of two masculine identities among the Palestinian youth of Jerusalem—the dod (a transgressive and lumpen-like countercultural figure) and the gada‘ (a brave man who fearlessly confronts the occupier)—through the lyrics of prominent Palestinian rappers, this article argues that these two modes of identification contribute to the creation of new representational politics and spaces of belonging among disaffected Palestinian youth. These developments in turn structure how resistance is understood and practiced by a generation of Palestinians consuming a new wave of Palestinian rap that challenges the neoliberal pacification of Palestinian society.</em></p>
</details>


## Work in Progress

- "Know Thy Neighbour as Thyself": The Effect of Outgroups on Contentious Politics
<details>
  <summary><em>Abstract</em></summary>
  <p><em>How does local exposure between two ethnic groups in conflict affect contentious activity at the local level? Prevailing studies of contentious politics and social movements have highlighted the role of expanded political opportunity structures and network effects as important determinants for the onset of contentious activity. This paper extends such analysis by focusing on the understudied role of ethnic tension and exposure in driving contentious activity. Leveraging a novel event dataset of contentious activity during the 1936-1939 Arab Revolt in Palestine, this paper uses a two-stage least squares (2SLS) model with a shift-share instrument to examine how local exposure between two ethnic groups in conflict influences the rate and intensity of contentious activity at the local level. I find that local inter-ethnic exposure is associated with an increase in Palestinian contentious activity, and that this effect is principally driven by a mechanism of resentment – rather than opportunity cost or appropriation. This suggests that Palestinian exposure to Jewish communities may have intensified the destructive and punitive dimensions of Palestinian mobilisation.</em></p>
</details>
- Conflict and Conciliation: Elite Mobilisation and Conflict under the British Mandate of Palestine, 1918-1930


- The variable effects of repression on mobilisation in Mandatory Palestine


## Other Projects

- The effect of exposure to protests on 
<details>
  <summary><em>Summary</em></summary>
  <p><em>An empirical exploration of the causal effects of exposure to pro-Palestine protests in the UK on the political behaviour of bystanders and onlookers.</em></p>
</details>

